/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type SneakerDetail = {
  _id: string;
  _type: "sneakerDetail";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sizeLabel?: string;
  sizeGuideLabel?: string;
  sizeGuideImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  skuLabel?: string;
  contactLabel?: string;
  social?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "social";
  }>;
};

export type Sort = {
  _id: string;
  _type: "sort";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  sortByLabel?: string;
  polularLabel?: string;
  priceAscLabel?: string;
  priceDescLabel?: string;
};

export type SneakerCount = {
  _id: string;
  _type: "sneakerCount";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  countLabel?: string;
};

export type Filter = {
  _id: string;
  _type: "filter";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandLabel?: string;
  collectionLabel?: string;
  sizeLabel?: string;
  priceLabel?: string;
  resetLabel?: string;
  applyLabel?: string;
};

export type Footer = {
  _id: string;
  _type: "footer";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  button?: Link;
  logo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      _key: string;
    } & Color>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  socialPlatform?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "social";
  }>;
  additionalInformation?: Array<string>;
  socialPlatformIcon?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "social";
  }>;
};

export type Social = {
  _id: string;
  _type: "social";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  socialPlatform?: "facebook" | "instagram" | "zalo" | "email" | "phoneNumber" | "website";
  title?: string;
  link?: Link;
};

export type Header = {
  _id: string;
  _type: "header";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  logo?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      _key: string;
    } & Color>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  links?: Array<{
    _key: string;
  } & Link>;
};

export type RichText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    _key: string;
  } & Color>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type Banner = {
  _id: string;
  _type: "banner";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
};

export type Trending = {
  _id: string;
  _type: "trending";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  viewAllLink?: Link;
  sneakers?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "sneaker";
  }>;
};

export type Link = {
  _type: "link";
  text?: string;
  url?: string;
};

export type Size = {
  _type: "size";
  size?: number;
  price?: number;
  out_of_stock?: boolean;
};

export type Sneaker = {
  _id: string;
  _type: "sneaker";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  images?: Array<{
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
    _key: string;
  }>;
  sizes?: Array<{
    _key: string;
  } & Size>;
  sku?: string;
  price?: number;
  content?: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "normal" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "blockquote";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }>;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  collection?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "collection";
  };
};

export type Collection = {
  _id: string;
  _type: "collection";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type Color = {
  _type: "color";
  hex?: string;
  alpha?: number;
  hsl?: HslaColor;
  hsv?: HsvaColor;
  rgb?: RgbaColor;
};

export type RgbaColor = {
  _type: "rgbaColor";
  r?: number;
  g?: number;
  b?: number;
  a?: number;
};

export type HsvaColor = {
  _type: "hsvaColor";
  h?: number;
  s?: number;
  v?: number;
  a?: number;
};

export type HslaColor = {
  _type: "hslaColor";
  h?: number;
  s?: number;
  l?: number;
  a?: number;
};

export type AllSanitySchemaTypes = SanityImagePaletteSwatch | SanityImagePalette | SanityImageDimensions | SanityFileAsset | Geopoint | SneakerDetail | Sort | SneakerCount | Filter | Footer | Social | Header | RichText | Banner | Trending | Link | Size | Sneaker | Collection | Brand | SanityImageCrop | SanityImageHotspot | SanityImageAsset | SanityAssetSourceData | SanityImageMetadata | Slug | Color | RgbaColor | HsvaColor | HslaColor;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./src/components/filter-provider.tsx
// Variable: filterQuery
// Query: {    "brands": *[_type == "brand" && _id in array::unique(*[_type == "sneaker"].brand._ref)]{        _id,        name,        "slug": slug.current    },    "collections": *[_type == "collection" && _id in array::unique(*[_type == "sneaker"].collection._ref)]{        _id,        name,        "slug": slug.current    },    "sizes": array::unique(*[_type == "sneaker" && defined(sizes[out_of_stock != true].size)].sizes[out_of_stock != true].size),    "minPrice": math::min(*[_type == "sneaker" && defined(price)].price),    "maxPrice": math::max(*[_type == "sneaker" && defined(price)].price)  }
export type FilterQueryResult = {
  brands: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
  }>;
  collections: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
  }>;
  sizes: Array<number | null>;
  minPrice: number | null;
  maxPrice: number | null;
};
// Variable: filterLabelQuery
// Query: *[_type == "filter"][0]{    brandLabel,    collectionLabel,    sizeLabel,    priceLabel,    resetLabel,    applyLabel  }
export type FilterLabelQueryResult = {
  brandLabel: string | null;
  collectionLabel: string | null;
  sizeLabel: string | null;
  priceLabel: string | null;
  resetLabel: string | null;
  applyLabel: string | null;
} | null;

// Source: ./src/components/footer.tsx
// Variable: footerQuery
// Query: *[_type == "footer"][0]{    title,    logo,    additionalInformation,    'socialPlatformIcon': socialPlatformIcon[]->{      socialPlatform,      link    },    'socialPlatform': socialPlatform[]->{      title,      link    },    button{      text    },    links[]{_key, url, text}    }
export type FooterQueryResult = {
  title: string | null;
  logo: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      _key: string;
    } & Color>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  additionalInformation: Array<string> | null;
  socialPlatformIcon: Array<{
    socialPlatform: "email" | "facebook" | "instagram" | "phoneNumber" | "website" | "zalo" | null;
    link: Link | null;
  }> | null;
  socialPlatform: Array<{
    title: string | null;
    link: Link | null;
  }> | null;
  button: {
    text: string | null;
  } | null;
  links: null;
} | null;

// Source: ./src/components/header.tsx
// Variable: headerQuery
// Query: *[_type == "header"][0]{    logo,    links[]{_key, url, text}    }
export type HeaderQueryResult = {
  logo: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      _key: string;
    } & Color>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
  links: Array<{
    _key: string;
    url: string | null;
    text: string | null;
  }> | null;
} | null;

// Source: ./src/components/hero.tsx
// Variable: bannerQuery
// Query: *[_type == "banner"][0]{    images[]{_key, 'ref':asset._ref}    }
export type BannerQueryResult = {
  images: Array<{
    _key: string;
    ref: string | null;
  }> | null;
} | null;

// Source: ./src/components/product-count.tsx
// Variable: productCountQuery
// Query: count(*[_type == "sneaker"       && (!defined($brands) || brand->slug.current in $brands)      && (!defined($collections) || collection->slug.current in $collections)      && (!defined($sizes) || count((sizes[out_of_stock != true].size)[@ in $sizes]) > 0)      && (!defined($minPrice) || price >= $minPrice)      && (!defined($maxPrice) || price <= $maxPrice)    ])
export type ProductCountQueryResult = number;
// Variable: sneakerCountQuery
// Query: *[_type == "sneakerCount"][0]{    countLabel  }
export type SneakerCountQueryResult = {
  countLabel: string | null;
} | null;

// Source: ./src/components/product-detail.tsx
// Variable: sneakerQuery
// Query: *[_type == "sneaker" && slug.current == $sneakerSlug][0]{    name,    "brand": brand->name,    "collection": collection->name,    price,    "sizes": sizes[]{_key, size, price, out_of_stock},    description,    "images": images[]{      "key": _key,      "ref": asset._ref    },    sku,    content,  }
export type SneakerQueryResult = {
  name: string | null;
  brand: string | null;
  collection: string | null;
  price: number | null;
  sizes: Array<{
    _key: string;
    size: number | null;
    price: number | null;
    out_of_stock: boolean | null;
  }> | null;
  description: null;
  images: Array<{
    key: string;
    ref: string | null;
  }> | null;
  sku: string | null;
  content: Array<{
    children?: Array<{
      marks?: Array<string>;
      text?: string;
      _type: "span";
      _key: string;
    }>;
    style?: "blockquote" | "h1" | "h2" | "h3" | "h4" | "h5" | "h6" | "normal";
    listItem?: "bullet" | "number";
    markDefs?: Array<{
      href?: string;
      _type: "link";
      _key: string;
    }>;
    level?: number;
    _type: "block";
    _key: string;
  }> | null;
} | null;
// Variable: sneakerDetailQuery
// Query: *[_type == "sneakerDetail"][0]{    sizeLabel,    sizeGuideLabel,    "sizeGuideImage": sizeGuideImage.asset._ref,    skuLabel,    contactLabel,    social[]->{      _id,      socialPlatform,      title,      link}  }
export type SneakerDetailQueryResult = {
  sizeLabel: string | null;
  sizeGuideLabel: string | null;
  sizeGuideImage: string | null;
  skuLabel: string | null;
  contactLabel: string | null;
  social: Array<{
    _id: string;
    socialPlatform: "email" | "facebook" | "instagram" | "phoneNumber" | "website" | "zalo" | null;
    title: string | null;
    link: Link | null;
  }> | null;
} | null;

// Source: ./src/components/product-list-provider.tsx
// Variable: sneakerListQueryAsc
// Query: *[_type == "sneaker"     && (!defined($brands) || brand->slug.current in $brands)    && (!defined($collections) || collection->slug.current in $collections)    && (!defined($sizes) || count((sizes[out_of_stock != true].size)[@ in $sizes]) > 0)    && (!defined($minPrice) || price >= $minPrice)    && (!defined($maxPrice) || price <= $maxPrice)    // && (!defined($lastAscs) || !defined($lastIdsAsc) || price > $lastAscs || (price == $lastAscs && _id > $lastIdsAsc))    ]|order(price asc)[$first...$last]{      _id,      "slug": slug.current,      name,      price,      "brand": brand->name,      "image": images[0].asset._ref    }
export type SneakerListQueryAscResult = Array<{
  _id: string;
  slug: string | null;
  name: string | null;
  price: number | null;
  brand: string | null;
  image: string | null;
}>;
// Variable: sneakerListQueryDesc
// Query: *[_type == "sneaker"     && (!defined($brands) || brand->slug.current in $brands)    && (!defined($collections) || collection->slug.current in $collections)    && (!defined($sizes) || count((sizes[out_of_stock != true].size)[@ in $sizes]) > 0)    && (!defined($minPrice) || price >= $minPrice)    && (!defined($maxPrice) || price <= $maxPrice)    // && (!defined($lastDescs) || !defined($lastIdsDesc) || price > $lastDescs || (price == $lastDescs && _id > $lastIdsDesc))    ]|order(price desc)[$first...$last]{      _id,      "slug": slug.current,      name,      price,      "brand": brand->name,      "image": images[0].asset._ref    }
export type SneakerListQueryDescResult = Array<{
  _id: string;
  slug: string | null;
  name: string | null;
  price: number | null;
  brand: string | null;
  image: string | null;
}>;
// Variable: sneakerListQueryPopular
// Query: *[_type == "sneaker"     && (!defined($brands) || brand->slug.current in $brands)    && (!defined($collections) || collection->slug.current in $collections)    && (!defined($sizes) || count((sizes[out_of_stock != true].size)[@ in $sizes]) > 0)    && (!defined($minPrice) || price >= $minPrice)    && (!defined($maxPrice) || price <= $maxPrice)    //maxPriceDO    ][$first...$last]{      _id,      "slug": slug.current,      name,      price,      "brand": brand->name,      "image": images[0].asset._ref    }
export type SneakerListQueryPopularResult = Array<{
  _id: string;
  slug: string | null;
  name: string | null;
  price: number | null;
  brand: string | null;
  image: string | null;
}>;

// Source: ./src/components/sort-provider.tsx
// Variable: sortQuery
// Query: *[_type == "sort"][0]{        sortByLabel,        polularLabel,        priceAscLabel,        priceDescLabel  }
export type SortQueryResult = {
  sortByLabel: string | null;
  polularLabel: string | null;
  priceAscLabel: string | null;
  priceDescLabel: string | null;
} | null;

// Source: ./src/components/trending.tsx
// Variable: trendingQuery
// Query: *[_type == "trending"][0]{    title,    viewAllLink,    'sneakers': sneakers[]->{      _id,      name,      price,      "slug":slug.current,      "brand":brand->name,      "image":images[0].asset._ref,    }}
export type TrendingQueryResult = {
  title: string | null;
  viewAllLink: Link | null;
  sneakers: Array<{
    _id: string;
    name: string | null;
    price: number | null;
    slug: string | null;
    brand: string | null;
    image: string | null;
  }> | null;
} | null;

// Source: ./src/app/(app)/sneakers/[slug]/page.tsx
// Variable: sneakerNameQuery
// Query: *[_type == "sneaker" && slug.current == $sneakerSlug][0]{    name,  }
export type SneakerNameQueryResult = {
  name: string | null;
} | null;

// Query TypeMap
import "@sanity/client";
declare module "@sanity/client" {
  interface SanityQueries {
    "{\n    \"brands\": *[_type == \"brand\" && _id in array::unique(*[_type == \"sneaker\"].brand._ref)]{\n        _id,\n        name,\n        \"slug\": slug.current\n    },\n    \"collections\": *[_type == \"collection\" && _id in array::unique(*[_type == \"sneaker\"].collection._ref)]{\n        _id,\n        name,\n        \"slug\": slug.current\n    },\n    \"sizes\": array::unique(*[_type == \"sneaker\" && defined(sizes[out_of_stock != true].size)].sizes[out_of_stock != true].size),\n    \"minPrice\": math::min(*[_type == \"sneaker\" && defined(price)].price),\n    \"maxPrice\": math::max(*[_type == \"sneaker\" && defined(price)].price)\n  }": FilterQueryResult;
    "*[_type == \"filter\"][0]{\n    brandLabel,\n    collectionLabel,\n    sizeLabel,\n    priceLabel,\n    resetLabel,\n    applyLabel\n  }": FilterLabelQueryResult;
    "*[_type == \"footer\"][0]{\n    title,\n    logo,\n    additionalInformation,\n    'socialPlatformIcon': socialPlatformIcon[]->{\n      socialPlatform,\n      link\n    },\n    'socialPlatform': socialPlatform[]->{\n      title,\n      link\n    },\n    button{\n      text\n    },\n    links[]{_key, url, text}\n    }": FooterQueryResult;
    "*[_type == \"header\"][0]{\n    logo,\n    links[]{_key, url, text}\n    }": HeaderQueryResult;
    "*[_type == \"banner\"][0]{\n    images[]{_key, 'ref':asset._ref}\n    }": BannerQueryResult;
    "count(*[_type == \"sneaker\" \n      && (!defined($brands) || brand->slug.current in $brands)\n      && (!defined($collections) || collection->slug.current in $collections)\n      && (!defined($sizes) || count((sizes[out_of_stock != true].size)[@ in $sizes]) > 0)\n      && (!defined($minPrice) || price >= $minPrice)\n      && (!defined($maxPrice) || price <= $maxPrice)\n    ])": ProductCountQueryResult;
    "*[_type == \"sneakerCount\"][0]{\n    countLabel\n  }": SneakerCountQueryResult;
    "*[_type == \"sneaker\" && slug.current == $sneakerSlug][0]{\n    name,\n    \"brand\": brand->name,\n    \"collection\": collection->name,\n    price,\n    \"sizes\": sizes[]{_key, size, price, out_of_stock},\n    description,\n    \"images\": images[]{\n      \"key\": _key,\n      \"ref\": asset._ref\n    },\n    sku,\n    content,\n  }": SneakerQueryResult;
    "*[_type == \"sneakerDetail\"][0]{\n    sizeLabel,\n    sizeGuideLabel,\n    \"sizeGuideImage\": sizeGuideImage.asset._ref,\n    skuLabel,\n    contactLabel,\n    social[]->{\n      _id,\n      socialPlatform,\n      title,\n      link}\n  }": SneakerDetailQueryResult;
    "*[_type == \"sneaker\" \n    && (!defined($brands) || brand->slug.current in $brands)\n    && (!defined($collections) || collection->slug.current in $collections)\n    && (!defined($sizes) || count((sizes[out_of_stock != true].size)[@ in $sizes]) > 0)\n    && (!defined($minPrice) || price >= $minPrice)\n    && (!defined($maxPrice) || price <= $maxPrice)\n    // && (!defined($lastAscs) || !defined($lastIdsAsc) || price > $lastAscs || (price == $lastAscs && _id > $lastIdsAsc))\n    ]|order(price asc)[$first...$last]{\n      _id,\n      \"slug\": slug.current,\n      name,\n      price,\n      \"brand\": brand->name,\n      \"image\": images[0].asset._ref\n    }": SneakerListQueryAscResult;
    "*[_type == \"sneaker\" \n    && (!defined($brands) || brand->slug.current in $brands)\n    && (!defined($collections) || collection->slug.current in $collections)\n    && (!defined($sizes) || count((sizes[out_of_stock != true].size)[@ in $sizes]) > 0)\n    && (!defined($minPrice) || price >= $minPrice)\n    && (!defined($maxPrice) || price <= $maxPrice)\n    // && (!defined($lastDescs) || !defined($lastIdsDesc) || price > $lastDescs || (price == $lastDescs && _id > $lastIdsDesc))\n    ]|order(price desc)[$first...$last]{\n      _id,\n      \"slug\": slug.current,\n      name,\n      price,\n      \"brand\": brand->name,\n      \"image\": images[0].asset._ref\n    }": SneakerListQueryDescResult;
    "*[_type == \"sneaker\" \n    && (!defined($brands) || brand->slug.current in $brands)\n    && (!defined($collections) || collection->slug.current in $collections)\n    && (!defined($sizes) || count((sizes[out_of_stock != true].size)[@ in $sizes]) > 0)\n    && (!defined($minPrice) || price >= $minPrice)\n    && (!defined($maxPrice) || price <= $maxPrice)\n    //maxPriceDO\n    ][$first...$last]{\n      _id,\n      \"slug\": slug.current,\n      name,\n      price,\n      \"brand\": brand->name,\n      \"image\": images[0].asset._ref\n    }": SneakerListQueryPopularResult;
    "*[_type == \"sort\"][0]{\n        sortByLabel,\n        polularLabel,\n        priceAscLabel,\n        priceDescLabel\n  }": SortQueryResult;
    "*[_type == \"trending\"][0]{\n    title,\n    viewAllLink,\n    'sneakers': sneakers[]->{\n      _id,\n      name,\n      price,\n      \"slug\":slug.current,\n      \"brand\":brand->name,\n      \"image\":images[0].asset._ref,\n    }}": TrendingQueryResult;
    "*[_type == \"sneaker\" && slug.current == $sneakerSlug][0]{\n    name,\n  }": SneakerNameQueryResult;
  }
}
