import type { Metadata } from "next";
import "./globals.css";
import { ClientProviders } from "./provider";
import { gilroy } from "~/utils/font/gilroy";
import { beVietnamPro } from "~/utils/font/be-vietnam-pro";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`text-neutral-900 ${gilroy.variable} ${beVietnamPro.className}`}>
        <ClientProviders>{children}</ClientProviders>
      </body>
    </html>
  );
}
